# Generated by Django 3.2 on 2023-09-30 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0012_review_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='rating',
        ),
        migrations.AddField(
            model_name='title',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
